const y = 10;

try {
  y = 2;
} catch (err) {
  console.log(`Erro: ${err}`);
}
